# Generated by Django 4.1.3 on 2022-11-13 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('numero_resi', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('dueño_resi', models.CharField(max_length=30)),
                ('telefono_resi', models.IntegerField()),
                ('mail_resi', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('EP', 'En Espera a Entregar'), ('ET', 'Entregado'), ('NET', 'No Entregado')], default='EP', max_length=30)),
                ('conserje', models.ForeignKey(limit_choices_to={'groups__name': 'Conserje'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
