# Generated by Django 4.1.3 on 2022-11-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('En Espera a Entregar', 'En Espera a Entregar'), ('Entregado', 'Entregado'), ('No Entregado', 'No Entregado')], default='En Espera a Entregar', max_length=30),
        ),
    ]
